CruGlobal/android-gto-support

gto-support-api/build.gradle, gto-support-api/src/main/java/org/ccci/gto/android/common/api/AbstractApi.java, gto-support-api/src/main/java/org/ccci/gto/android/common/api/AbstractGtoSmxApi.java, gto-support-api/src/main/java/org/ccci/gto/android/common/api/MultipartFormOutputWriter.java
This adds support for submitting multipart/form-data POST requests to an API.
The current need for this is Stories support for GMA/iShare/TBD, the upload image API only accepts multipart/form-data requests.
=> Multipart form support

gto-support-core/src/main/java/org/ccci/gto/android/common/widget/RatioLayout.java, gto-support-core/src/main/res/values/attrs.xml
update RatioLayout to support AT_MOST measurement specs
=> port RatioLayout from Ekko

gto-support-eventbus/build.gradle, gto-support-eventbus/src/main/AndroidManifest.xml, gto-support-eventbus/src/main/java/org/ccci/gto/android/common/eventbus/content/CursorEventBusLoader.java, gto-support-eventbus/src/main/java/org/ccci/gto/android/common/eventbus/content/EventBusLoaderHelper.java, gto-support-eventbus/src/main/java/org/ccci/gto/android/common/eventbus/content/EventBusSubscriber.java, settings.gradle
Tested on my local machine, seems to work as intended.
=> Eventbus loader

build.gradle, gto-support-core/build.gradle, gto-support-db-async/build.gradle, gto-support-db-async/src/main/AndroidManifest.xml, gto-support-db-async/src/main/java/org/ccci/gto/android/common/db/async/AbstractAsyncDao.java, settings.gradle
more methods will be added as we need them.
=> first pass at an Async DAO

gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/content/AsyncTaskBroadcastReceiverLoader.java, gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/content/AsyncTaskBroadcastReceiverSharedPreferencesChangeLoader.java, gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/content/AsyncTaskSharedPreferencesChangeLoader.java, gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/content/BroadcastReceiverLoaderHelper.java, gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/content/CursorBroadcastReceiverLoader.java, gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/content/CursorBroadcastReceiverSharedPreferencesChangeLoader.java, gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/content/SharedPreferencesChangeLoaderHelper.java, gto-support-eventbus/src/main/java/org/ccci/gto/android/common/eventbus/content/CursorEventBusLoader.java, gto-support-eventbus/src/main/java/org/ccci/gto/android/common/eventbus/content/EventBusLoaderHelper.java, gto-support-eventbus/src/main/java/org/ccci/gto/android/common/eventbus/content/EventBusSubscriber.java
=> Content loaders

gto-support-db/src/main/java/org/ccci/gto/android/common/db/Expression.java, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Table.java, gto-support-db/src/testCommon/java/org/ccci/gto/android/common/db/Contract.java
this makes usage a bit more straight forward IMO
=> move field method to table object

build.gradle, gto-support-api/build.gradle, gto-support-gson/build.gradle, gto-support-gson/src/main/AndroidManifest.xml, gto-support-gson/src/main/java/org/ccci/gto/android/common/gson/GsonIgnore.java, gto-support-gson/src/main/java/org/ccci/gto/android/common/gson/GsonIgnoreExclusionStrategy.java, settings.gradle
this moves some of the work @wrandall22 did on Gson for MPDX last sprint to a common reusable library.
=> `@GsonIgnore` annotation

gto-support-core/src/main/java/org/ccci/gto/android/common/util/CollectionUtils.java, gto-support-core/src/test/java/org/ccci/gto/android/common/util/CollectionUtilsTest.java, gto-support-jsonapi/build.gradle, gto-support-jsonapi/src/androidTest/java/org/ccci/gto/android/common/jsonapi/JsonApiConverterIT.java, gto-support-jsonapi/src/main/java/org/ccci/gto/android/common/jsonapi/JsonApiConverter.java
- fixed the generated/parsed format for relationships
- added support for parsing attributes from included objects
- added support for parsing relationship collections
=> Jsonapi improvements

gto-support-jsonapi-retrofit2/build.gradle, gto-support-jsonapi-retrofit2/src/main/java/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiParams.java, gto-support-jsonapi-retrofit2/src/test/java/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiParamsTest.java
=> create JsonApiParams Map

gto-support-db/src/main/java/org/ccci/gto/android/common/db/support/v4/content/DaoCursorLoader.java
there is no need for this to be abstract
=> make DaoCursorLoader concrete

gto-support-db/src/main/java/org/ccci/gto/android/common/db/AbstractDao.java, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Expression.java, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Transaction.java, gto-support-jsonapi/src/main/java/org/ccci/gto/android/common/jsonapi/util/Includes.java
- support reuse of Transaction objects
- cache some string concatenation
=> Performance improvements

gto-support-db-async/src/main/java/org/ccci/gto/android/common/db/async/AbstractAsyncDao.java, gto-support-db/src/main/java/org/ccci/gto/android/common/db/AbstractDao.java
Also, return the number of rows affected by an update
=> Add support for custom conflictAlgorithms for update methods

build.gradle, gto-support-appcompat/src/main/java/android/support/v7/widget/AppCompatButtonImpl.java, gto-support-appcompat/src/main/java/android/support/v7/widget/AppCompatCompoundDrawableHelper.java, gto-support-appcompat/src/main/java/android/support/v7/widget/AppCompatTextCompoundDrawableHelper.java, gto-support-appcompat/src/main/java/android/support/v7/widget/AppCompatTextViewImpl.java, gto-support-appcompat/src/main/java/android/support/v7/widget/ReflectionUtils.java, gto-support-appcompat/src/main/res/values/attrs.xml, gto-support-recyclerview-advrecyclerview/build.gradle
- Support TintLists
- Support Vector compoundDrawables
=> add compoundDrawable compat support

gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/util/WeakLruCache.java, gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/util/WeakMultiKeyLruCache.java, gto-support-core/src/test/java/org/ccci/gto/android/common/support/v4/util/WeakLruCacheTest.java, gto-support-core/src/test/java/org/ccci/gto/android/common/support/v4/util/WeakMultiKeyLruCacheTest.java
work around a few corner case bugs that could cause cache corruption
=> WeakLruCache corruption

gto-support-db/src/main/java/org/ccci/gto/android/common/db/AbstractDao.java, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Closure.java
This removes often repeated transaction handling logic.
=> add inTransaction(Closure) method

gto-support-util/src/main/java/org/ccci/gto/android/common/util/DynamicSSLSocketFactory.java
Move Logic for a custom SSLSocket Factory to this Support Library.
=> Add DynamicSSLSocketFactory

gto-support-util/build.gradle, gto-support-util/proguard-consumer.pro, gto-support-util/src/main/java/org/ccci/gto/android/common/util/DynamicSSLSocketFactory.java
Needed to change delegate name to support OKHttpClient using injection to get TrustManager
=> change delegate name.

gto-support-jsonapi/src/androidTest/java/org/ccci/gto/android/common/jsonapi/JsonApiConverterAttributeCollectionsIT.java, gto-support-jsonapi/src/main/java/org/ccci/gto/android/common/jsonapi/JsonApiConverter.java
This will support using a Collection type for regular attributes and not just relationships
=> jsonapi collection attributes

build.gradle, gto-support-db-livedata/src/main/java/org/ccci/gto/android/common/db/LiveDataDao.kt, gto-support-db/build.gradle, gto-support-db/src/main/java/org/ccci/gto/android/common/db/AbstractDao.kt, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Transaction.kt, gto-support-db/src/test/java/org/ccci/gto/android/common/db/AbstractDaoClassInvalidationTest.kt, gto-support-db/src/test/java/org/ccci/gto/android/common/db/AbstractDaoExtensionFunctionTest.kt, gto-support-util/src/main/java/org/ccci/gto/android/common/util/kotlin/ThreadLocalDelegate.kt
This implements a transaction aware class invalidation framework. This will automatically refresh LiveData objects when changes are made to the database.
=> Automatic invalidation of LiveData objects

gto-support-dagger/src/main/java/org/ccci/gto/android/common/dagger/eager/EagerModule.kt, gto-support-dagger/src/main/java/org/ccci/gto/android/common/dagger/eager/EagerSingleton.kt, gto-support-dagger/src/main/java/org/ccci/gto/android/common/dagger/eager/EagerSingletonInitializer.kt
This will allow singletons to be initialized only when a UI is visible (activity start) vs always being initialized
=> Support initializing singletons on activity start instead of application start

gto-support-moshi/src/main/java/org/ccci/gto/android/common/moshi/adapter/StringifyJsonAdapterFactory.kt
this annotation will convert complex json to a string
=> create a Stringify moshi annotation

gto-support-util/src/main/java/org/ccci/gto/android/common/util/content/Context.kt
this will support overriding the Locale for the specified Context object
=> create a localize method for Context objects

gto-support-material-components/src/main/java/org/ccci/gto/android/common/material/chip/Chip.kt, gto-support-material-components/src/main/java/org/ccci/gto/android/common/material/chip/databinding/ChipBindingAdapter.kt, gto-support-material-components/src/main/java/org/ccci/gto/android/common/material/shape/AngledCutCornerTreatment.kt, gto-support-material-components/src/test/java/org/ccci/gto/android/common/material/chip/ChipTest.kt, gto-support-material-components/src/test/java/org/ccci/gto/android/common/material/shape/AngledCutCornerTreatmentTest.kt, gto-support-util/src/test/java/org/ccci/gto/android/common/util/graphics/ColorTestUtils.kt
- Chip elevation compat property
- AngledCutCornerTreatment that provides a customizable cut corner for material shapes
=> Material Component utils

testing/gto-support-timber/src/main/java/org/ccci/gto/android/common/testing/timber/ExceptionRaisingTree.kt
this will resurface any exceptions that might have been swallowed elsewhere
=> rethrow the last seen exception when uprooting ExceptionRaisingTree

gto-support-androidx-viewpager2/src/main/java/org/ccci/gto/android/common/androidx/viewpager2/widget/ViewPager2.kt, gto-support-androidx-viewpager2/src/test/java/org/ccci/gto/android/common/androidx/viewpager2/widget/ViewPager2HeightWrapContentTest.kt, gto-support-androidx-viewpager2/src/test/java/org/ccci/gto/android/common/androidx/viewpager2/widget/ViewPager2MaintainVisibleItemTest.kt
This is a workaround for https://issuetracker.google.com/issues/181785654
=> GT-1092 Support maintaining the visible page when modifying the ViewPager2 structure

gto-support-kotlin-coroutines/build.gradle, gto-support-kotlin-coroutines/src/main/java/org/ccci/gto/android/common/kotlin/coroutines/SharedPreferencesFlow.kt, gto-support-kotlin-coroutines/src/test/java/org/ccci/gto/android/common/kotlin/coroutines/SharedPreferencesFlowTest.kt
This will produce a Flow of the current value for a specified SharedPreference key
=> Add Coroutines Flow extension methods for SharedPreferences

.github/workflows/build.yml, gradle.properties
- utilize the gradle build action
- enable the build cache and enable parallel mode by default
=> Make some build speed improvements

gto-support-db-coroutines/src/main/kotlin/org/ccci/gto/android/common/db/CoroutinesDao.kt, gto-support-db-coroutines/src/main/kotlin/org/ccci/gto/android/common/db/CoroutinesFlowDao.kt, gto-support-db-coroutines/src/test/kotlin/org/ccci/gto/android/common/db/CoroutinesFlowDaoTest.kt, gto-support-db/src/main/java/org/ccci/gto/android/common/db/AbstractDao.kt, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Dao.kt
- add framework for tracking services in a Dao
- use a restricted dispatcher for CoroutinesFlowDao
=> Use a limited parallelism dispatcher for the CoroutineDao

gto-support-db-async/src/main/java/org/ccci/gto/android/common/db/AsyncDao.kt, gto-support-db-coroutines/src/main/kotlin/org/ccci/gto/android/common/db/CoroutinesAsyncDao.kt, gto-support-db-coroutines/src/main/kotlin/org/ccci/gto/android/common/db/CoroutinesDao.kt, gto-support-db-coroutines/src/main/kotlin/org/ccci/gto/android/common/db/CoroutinesFlowDao.kt, gto-support-db-coroutines/src/test/kotlin/org/ccci/gto/android/common/db/CoroutinesFlowDaoTest.kt, gto-support-db-livedata/src/main/kotlin/org/ccci/gto/android/common/db/LiveDataDao.kt, gto-support-db/src/main/java/org/ccci/gto/android/common/db/AbstractDao.kt, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Dao.kt, settings.gradle.kts
Introduce a `CoroutinesAsyncDao` which will allow us to asynchronously trigger db queries.
This will be used in GodTools to asynchronously track tool opens
=> CoroutinesAsyncDao

gto-support-appcompat/src/main/kotlin/androidx/appcompat/widget/AppCompatButtonImpl.kt
=> deprecate AppCompatButtonImpl

.github/workflows/build.yml, build.gradle.kts, gradle/libs.versions.toml
- replace jacoco with Kotlin Kover
- trigger kotlin kover report task from GHA
=> Kotlin Kover

gradle/libs.versions.toml
Reverts CruGlobal/android-gto-support#1137
=> Revert "Update dependency com.facebook.flipper:flipper to v0.132.0"

gradle/libs.versions.toml
Reverts CruGlobal/android-gto-support#1150
=> Revert "Update dependency com.facebook.flipper:flipper to v0.133.0"

gto-support-util/src/main/java/org/ccci/gto/android/common/util/os/BundleUtils.kt, gto-support-util/src/main/kotlin/org/ccci/gto/android/common/util/content/Intent+Locale.kt, gto-support-util/src/main/kotlin/org/ccci/gto/android/common/util/os/Bundle.kt, gto-support-util/src/test/java/org/ccci/gto/android/common/util/os/BundleUtilsTest.kt, gto-support-util/src/test/kotlin/org/ccci/gto/android/common/util/content/IntentLocaleTest.kt, gto-support-util/src/test/kotlin/org/ccci/gto/android/common/util/os/BundleTest.kt
- move Bundle extension methods to kotlin source directory
- move Bundle.*Locale functions to Bundle.kt
- move BundleTest to kotlin source directory
- move Bundle Locale tests to BundleTest
- create Intent extension methods for putting/getting a Locale
=> Locale extensions for Bundles and Intents

gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/Transformations.kt, gto-support-androidx-lifecycle/src/test/kotlin/org/ccci/gto/android/common/androidx/lifecycle/TransformationsCombineWithTest.kt
- add a non-extension combine for 2 LiveData objects
- add a unit test for new combine() method
=> Create new combine LiveData Transformation

gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/SavedStateHandle+Delegates.kt, gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/SavedStateHandle+StateFlow.kt, gto-support-androidx-lifecycle/src/test/kotlin/org/ccci/gto/android/common/androidx/lifecycle/SavedStateHandleDelegatesTest.kt, gto-support-androidx-lifecycle/src/test/kotlin/org/ccci/gto/android/common/androidx/lifecycle/SavedStateHandleStateFlowTest.kt
- add a getStateFlow extension method for SavedStateHandle
- create stateFlow delegates for SavedStateHandle
=> Add support for consuming SavedStateHandle as a StateFlow

build.gradle.kts, gradle/libs.versions.toml, gto-support-kotlin-coroutines/build.gradle.kts, gto-support-kotlin-coroutines/src/main/kotlin/org/ccci/gto/android/common/kotlin/coroutines/Flow+LiveData.kt, gto-support-kotlin-coroutines/src/test/kotlin/org/ccci/gto/android/common/kotlin/coroutines/FlowLiveDataTest.kt
- add a collectInto(MutableLiveData) extension method
- add a unit test for new collectInto extension method
=> Create a collectInto(MutableLiveData) extension method for Flows

gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/view/PicassoImageView.kt, gto-support-picasso/src/main/res/values/attrs.xml, gto-support-picasso/src/test/kotlin/org/ccci/gto/android/common/picasso/view/SimplePicassoImageViewTest.kt
- add a unit test for initializing the placeholder from xml
- make it possible to initialize the picasso file and picasso uri in layout xml
=> xml attributes to initialize picasso ImageView

gto-support-db-coroutines/src/main/kotlin/org/ccci/gto/android/common/db/CoroutinesFlowDao.kt, gto-support-db-coroutines/src/test/kotlin/org/ccci/gto/android/common/db/CoroutinesFlowDaoTest.kt
this will be used in GodTools to monitor for changes instead of relying on EventBus broadcasts
=> expose an invalidationFlow method

gto-support-db/src/main/java/org/ccci/gto/android/common/db/Expression.kt
- make `and` and `or` infix methods
- make all the comparison functions infix functions
=> Dao infix functions

buildSrc/src/main/kotlin/AndroidConfiguration.kt, buildSrc/src/main/kotlin/Project.kt, gradle/libs.versions.toml, gto-support-androidx-compose/build.gradle.kts, gto-support-androidx-compose/src/main/AndroidManifest.xml, gto-support-androidx-compose/src/main/kotlin/org/ccci/gto/android/common/androidx/compose/foundation/text/MinLinesHeightModifier.kt, settings.gradle.kts
- support enable Jetpack compose for gto-support libraries
- create a gto-support-androidx-compose module
- create a MinLinesHeightModifier based upon AOSP MaxLinesHeightModifier
=> GT-1529 create Modifier.minLinesHeight()

buildSrc/src/main/kotlin/AndroidConfiguration.kt, gradle/libs.versions.toml, gto-support-androidx-lifecycle/build.gradle.kts, gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/compose/OnLifecycleEvent.kt
These Composables can be used to trigger SideEffects when the LifecycleOwner triggers the corresponding Lifecycle events
=> provide `OnLifecycleEvent` and `OnResume` Composables

gto-support-facebook-flipper/build.gradle.kts, gto-support-facebook-flipper/proguard-consumer.pro, gto-support-scarlet/build.gradle.kts, gto-support-scarlet/proguard-consumer.pro, gto-support-util/src/main/kotlin/org/ccci/gto/android/common/util/content/Context.kt
- add a localizeIfPossible() util
- add some reusable proguard rules
=> Various utils for GodTools

gto-support-androidx-compose-material3/src/main/kotlin/org/ccci/gto/android/common/androidx/compose/material3/ui/appbar/AppBarAction.kt, gto-support-androidx-compose/src/main/kotlin/org/ccci/gto/android/common/androidx/compose/ui/text/Paragraph.kt, gto-support-androidx-compose/src/testDebug/kotlin/org/ccci/gto/android/common/androidx/compose/ui/text/ParagraphTest.kt
- add method to compute the width of a single line of text
- provide a composable framework to quickly define/render simple app bar actions
=> Create Composable for quickly rendering app bar actions

gto-support-okta/src/main/kotlin/org/ccci/gto/android/common/okta/authfoundation/credential/Credential+Flow.kt, gto-support-okta/src/test/kotlin/org/ccci/gto/android/common/okta/authfoundation/credential/CredentialFlowTest.kt
This change will cause userInfoFlow() to emit null if there is no data cached and fetching the data from the API fails for some reason.
The previous behavior would be the flow wouldn't emit anything if data wasn't cached and the user was offline. This led to consumers of this flow waiting indefinitely for something that may not happen.
=> Ensure userInfoFlow() emits null if offline and no data is cached

gto-support-compat/src/main/kotlin/org/ccci/gto/android/common/compat/os/BundleCompat.kt, gto-support-compat/src/test/kotlin/org/ccci/gto/android/common/compat/os/BundleCompatTest.kt, gto-support-sync/build.gradle.kts, gto-support-sync/src/main/java/org/ccci/gto/android/common/sync/swiperefreshlayout/widget/SwipeRefreshSyncHelper.kt
- create a getParcelableCompat method
- utilize getParcelableCompat method
=> create a getParcelableCompat extension method

gto-support-androidx-room/src/main/kotlin/org/ccci/gto/android/common/androidx/room/converter/Java8TimeConverters.kt, gto-support-androidx-room/src/test/kotlin/org/ccci/gto/android/common/androidx/room/converter/Java8TimeConvertersTest.kt
this type converter ignores nano-seconds
=> add room type converters for Instants

.github/workflows/build.yml
copied the logic added in this PR: https://github.com/CruGlobal/kotlin-mpp-godtools-tool-parser/pull/326
I had to tweak the logic to use the `master` branch instead of `main`
=> import trigger release logic from kotlin-mpp-godtools-shared build workflow

.github/workflows/build.yml
- make sure to reference the correct step id
- actions-ecosystem/action-push-tag@v1 is currently broken
=> Fix trigger release workflow

build.gradle.kts, gradle/libs.versions.toml
- remove unused snowplow dependency
- remove unused androidx cursoradapter dependency
- remove the old jdk8 kotlin stdlib library
=> Remove unused dependencies

gto-support-kotlin-coroutines/build.gradle.kts, gto-support-kotlin-coroutines/src/main/kotlin/org/ccci/gto/android/common/kotlin/coroutines/flow/net/Flow+ConnectivityManager.kt, gto-support-kotlin-coroutines/src/test/kotlin/org/ccci/gto/android/common/kotlin/coroutines/flow/net/FlowConnectivityManagerTest.kt
this method returns a flow that indicates if the device is connected to the internet or not
=> add a Context.isConnectedFlow() method

build-logic/src/main/kotlin/MultiplatformConfiguration.kt, build-logic/src/main/kotlin/gto-support.multiplatform-conventions.gradle.kts
- adjust how the multiplatform android target is configured
- remove unnecessary android sourceSets config
=> Adjust some Kotlin Multiplatform configuration

build-logic/src/main/kotlin/gto-support.multiplatform-conventions.gradle.kts, gradle.properties, gto-support-jsonapi-core/src/main/java/org/ccci/gto/android/common/jsonapi/JsonApiConverter.java, gto-support-jsonapi-core/src/main/kotlin/org/ccci/gto/android/common/jsonapi/util/Includes.kt, gto-support-jsonapi-core/src/test/kotlin/org/ccci/gto/android/common/jsonapi/JsonApiConverterCycleRelationshipTest.kt, gto-support-jsonapi-core/src/test/kotlin/org/ccci/gto/android/common/jsonapi/JsonApiConverterNullAttributesTest.kt, gto-support-jsonapi-core/src/test/kotlin/org/ccci/gto/android/common/jsonapi/JsonApiConverterOptionsTest.kt, gto-support-jsonapi-core/src/test/kotlin/org/ccci/gto/android/common/jsonapi/JsonApiConverterSparseFieldsetTest.kt, gto-support-jsonapi-core/src/test/kotlin/org/ccci/gto/android/common/jsonapi/util/IncludesTest.kt, gto-support-jsonapi-retrofit2/build.gradle.kts, gto-support-jsonapi-retrofit2/src/commonMain/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/BaseJsonApiParams.kt, gto-support-jsonapi-retrofit2/src/commonMain/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiConverterFactory.kt, gto-support-jsonapi-retrofit2/src/commonMain/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiParams.kt, gto-support-jsonapi-retrofit2/src/commonTest/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiConverterFactoryTest.kt, gto-support-jsonapi-retrofit2/src/commonTest/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiParamsTest.kt
- enable kotlin test dependency for all multiplatform modules
- support passing an Includes object to JsonApiParams
=> Support more directly using the Includes object with Retrofit

.github/codecov.yml, .github/workflows/build.yml, build-logic/src/main/kotlin/AndroidConfiguration.kt, build-logic/src/main/kotlin/Project.kt
- add build-logic to support test shards
- configure gha for 2 test shards
=> Enable Test Sharding for Android/JVM tests

gto-support-androidx-fragment/src/test/kotlin/org/ccci/gto/android/common/androidx/fragment/app/FragmentFindListenerTest.kt, gto-support-util/src/test/java/org/ccci/gto/android/common/util/DimensionUtilsTest.kt, gto-support-util/src/test/kotlin/org/ccci/gto/android/common/util/database/CursorTest.kt
- **convert FragmentFindListenerTest to use MockK**
- **update DimensionUtilsTest to utilize kotlin-test and MockK**
- **update CursorTest to utilize MockK**
=> Convert a few tests to MockK
