CruGlobal/android-gto-support

build.gradle, gto-support-api-base/build.gradle, gto-support-api-base/src/main/AndroidManifest.xml, gto-support-api-base/src/main/java/org/ccci/gto/android/common/api/Session.java, gto-support-api-base/src/main/java/org/ccci/gto/android/common/api/TheKeySession.java, gto-support-api-okhttp3/build.gradle, gto-support-api-okhttp3/lint.xml, gto-support-api-okhttp3/src/main/AndroidManifest.xml, gto-support-api-okhttp3/src/main/java/org/ccci/gto/android/common/api/okhttp3/ApiException.java, gto-support-api-okhttp3/src/main/java/org/ccci/gto/android/common/api/okhttp3/InvalidSessionApiException.java, gto-support-api-okhttp3/src/main/java/org/ccci/gto/android/common/api/okhttp3/interceptor/SessionInterceptor.java, gto-support-api/build.gradle, gto-support-api/src/main/java/org/ccci/gto/android/common/api/AbstractApi.java, gto-support-api/src/main/java/org/ccci/gto/android/common/api/AbstractGtoSmxApi.java, gto-support-api/src/main/java/org/ccci/gto/android/common/api/AbstractTheKeyApi.java, gto-support-core/build.gradle, gto-support-core/src/main/java/org/ccci/gto/android/common/util/SharedPreferencesCompat.java, gto-support-db/build.gradle, gto-support-newrelic/build.gradle, gto-support-picasso/build.gradle, gto-support-recyclerview/build.gradle, settings.gradle
This is based around the pre-existing session support for the native `HttpURLConnection` API.
The concept is that there is a `SessionInterceptor` that gets applied to all OkHttp3 network requests. The basic flow is:
1. Intercept a network request before it is sent
2. load a current session from preferences
3. if no valid current session exists, call out to external code to establish a new session
4. Attach the session to the request
5. proceed with executing the request
6. check the response to see if our session was invalid or not
7. if the session was invalid, delete the original loaded session
8. return the response
=> Common session interceptor for okhttp3

gto-support-api-okhttp3/src/main/java/org/ccci/gto/android/common/api/okhttp3/util/OkHttpClientUtil.java
This will depend on OkHttpClient builders to trigger `attachGlobalInterceptors`
=> add a util to define global network interceptors

gto-support-db/src/androidTest/java/org/ccci/gto/android/common/db/AbstractDaoIT.java, gto-support-db/src/androidTest/java/org/ccci/gto/android/common/db/util/CursorUtilsIT.java, gto-support-db/src/main/java/org/ccci/gto/android/common/db/util/CursorUtils.java, gto-support-db/src/testCommon/java/org/ccci/gto/android/common/db/Contract.java, gto-support-db/src/testCommon/java/org/ccci/gto/android/common/db/TestDao.java
The problem was that the default value was only being used if we didn't have the specified column in the result set, but not based on if the field was actually null.
We document this behavior to make the expected behavior clear.
=> fix a corner case where the database column is null

gto-support-jsonapi/src/androidTest/java/org/ccci/gto/android/common/jsonapi/JsonApiConverterIT.java, gto-support-jsonapi/src/main/java/org/ccci/gto/android/common/jsonapi/JsonApiConverter.java, gto-support-jsonapi/src/main/java/org/ccci/gto/android/common/jsonapi/annotation/JsonApiType.java
This will allow APIs that return the same objects under different types to be aliased to the same object
=> add support for JsonApiType aliases

.travis.yml, gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/transformation/MaskTransformation.java
It's possible a Picasso request is made with the MaskTransform, and then the launching context is finished before the request is resolved. We should protect against this leak.
=> Fix memory leak in MaskTransform

gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/adapter/ViewHolderPagerAdapter.java
This position may no longer exist
=> don't use the previous position within destroyItem.

gto-support-core/src/main/java/org/ccci/gto/android/common/support/v4/widget/MultiDrawerListener.java
This is no longer necessary since DrawerLayout natively supports multiple listeners
=> Deprecate MultiDrawerListener

gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/view/PicassoImageView.java, gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/view/SimplePicassoImageView.java
If Picasso has cached the processed image in memory, it will immediately set the image on the ImageView, which will request a layout that can't be honored. This can cause views to not re-measure themselves to adjust for different image sizes
=> Don't trigger update while we are currently in a layout pass

gto-support-leakcanary/src/main/java/org/ccci/gto/android/common/leakcanary/CrashlyticsLeakService.java
It's more important to get the beginning of a leak than the end of it
=> truncate leak crashlytics log

gto-support-db/src/main/java/org/ccci/gto/android/common/db/AbstractDao.java
We have been seeing locked db errors on ICS due to several threads running getCursor simultaneously.
=> wrap getCursor in a non-exclusive transaction

gto-support-util/src/main/java/org/ccci/gto/android/common/util/WeakTask.java
This will address a common use-case where we want to maintain a weak reference to an object to not leak memory if the object disappears before the runnable executes.
=> create a WeakRunnable class

gto-support-util/src/main/java/org/ccci/gto/android/common/util/view/ViewUtils.java, gto-support-util/src/test/java/org/ccci/gto/android/common/util/view/ViewUtilsTest.java
Fixes: https://console.firebase.google.com/u/0/project/godtools-b2f82/crashlytics/app/android:org.keynote.godtools.android/issues/5bd6d017f8b88c2963a6cbc3?time=last-ninety-days&sessionId=5BE646340071000153CED6F05CB1D896_DNE_0_v2
=> handle a different invalid pointer index exception thrown on Huawei devices

gto-support-realm/src/main/java/org/ccci/gto/android/common/realm/adapter/RealmDataBindingAdapter.kt, gto-support-recyclerview/src/main/java/org/ccci/gto/android/common/recyclerview/adapter/SimpleDataBindingAdapter.java
RecyclerViews separate binding data from view layout. Data Binding defers binding to improve performance. These features work against each other, so we should trigger any pending bindings during recyclerview binding logic
=> We should trigger executePendingBindings for DataBinding in a RecyclerView

gto-support-jsonapi/src/androidTest/java/org/ccci/gto/android/common/jsonapi/JsonApiConverterIT.java, gto-support-jsonapi/src/main/java/org/ccci/gto/android/common/jsonapi/JsonApiConverter.java, gto-support-jsonapi/src/main/java/org/ccci/gto/android/common/jsonapi/annotation/JsonApiAttribute.java
This allows the annotation to be defined as `@JsonApiAttribute("field")` instead of it needing to be `@JsonApiAttribute(name = "field")`
=> make it possible to specify a jsonapi attribute name as the value of the JsonApiAttribute annotation

gto-support-jsonapi/src/androidTest/java/org/ccci/gto/android/common/jsonapi/JsonApiConverterIT.java, gto-support-jsonapi/src/main/java/org/ccci/gto/android/common/jsonapi/JsonApiConverter.java, gto-support-jsonapi/src/main/java/org/ccci/gto/android/common/jsonapi/annotation/JsonApiAttribute.java
this will allow fields to be ignored by the serialization/deserialization processes independently
=> add serialize and deserialize booleans to JsonApiAttribute

gto-support-core/src/main/java/org/ccci/gto/android/common/drawable/LayerDrawableUtils.kt
provide an extension val to easily iterate over the children of a `LayerDrawable`
=> LayerDrawable.children extension property

gto-support-db-livedata/src/main/java/org/ccci/gto/android/common/db/LiveDataDao.kt
this should allow the following kotlin statement to work:
```kotlin
val obj: LiveData<Type?> = dao.findLiveData(id)
```
=> add an inline reified method to simplify `findLiveData` usage

gto-support-lifecycle/src/main/java/org/ccci/gto/android/common/lifecycle/CollectionLiveData.kt, gto-support-lifecycle/src/test/java/org/ccci/gto/android/common/lifecycle/databinding/CollectionLiveDataTests.kt
Instead of forcing modifications to be made via the LiveData object, enable making changes via the collection stored in LiveData
=> Collection LiveData adjustments

gto-support-lifecycle/build.gradle, gto-support-lifecycle/src/main/java/org/ccci/gto/android/common/lifecycle/LiveData.kt, gto-support-lifecycle/src/test/java/org/ccci/gto/android/common/lifecycle/databinding/LiveDataObserveOnceTest.kt
this will allow us to observe LiveData for data, but only receive a single callback with the first available value.
This will be used in the GodTools Manifest parsing refactor
=> LiveData.observeOnce() extension method

gto-support-db-livedata/build.gradle, gto-support-db-livedata/src/main/java/org/ccci/gto/android/common/db/LiveDataDao.kt, gto-support-db-livedata/src/test/java/org/ccci/gto/android/common/db/LiveDataRegistryTest.kt
if the internal registry was updated while we were processing an invalidation it would trigger a `ConcurrentModificationException`
=> GT-745 prevent ConcurrentModificationException in DB LiveData logic

gto-support-androidx-lifecycle/build.gradle, gto-support-androidx-lifecycle/src/main/java/org/ccci/gto/android/common/androidx/lifecycle/Lifecycle.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/LambdaLifecycleObserverTest.kt
This will allow us to easily trigger a lambda function when a lifecycle is being destroyed
=> GT-803 create a Lifecycle.onDestroy kotlin extension method

gto-support-androidx-lifecycle/src/main/java/androidx/lifecycle/LiveDataInternals.kt, gto-support-androidx-lifecycle/src/main/java/org/ccci/gto/android/common/androidx/lifecycle/Transformations.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/TransformationsTests.kt
this is a behavior change for `LiveData.combineWith` and `LiveData.switchCombineWith`. It affects when the initial combined value is available from the result `LiveData`, and when any Observer callback is first triggered.
This change actually makes the result `LiveData` line up with how `LiveData` is supposed to behave around initial values
=> Only emit a value in Transformations once the source LiveDatas have been initialized

gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/databinding/adapters/PicassoConverters.kt, gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/databinding/adapters/SimplePicassoImageViewBindingAdapter.kt
This only works for simple Transformations that don't take any constructor parameters.
=> add databinding converter to convert a string to an instance of a Transformation

gto-support-androidx-lifecycle/src/main/java/org/ccci/gto/android/common/androidx/lifecycle/EmptyLiveData.kt, gto-support-androidx-lifecycle/src/main/java/org/ccci/gto/android/common/androidx/lifecycle/ImmutableLiveData.kt, gto-support-androidx-lifecycle/src/main/java/org/ccci/gto/android/common/androidx/lifecycle/Transformations.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/BaseLiveDataTest.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/CollectionLiveDataTest.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/EmptyLiveDataTest.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/LiveDataViewModelObserverTest.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/TransformationsCombineWithTest.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/TransformationsFoldTest.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/TransformationsWithInitialValueTest.kt
adds:
- Adds an initial value to the LiveData before it loads the actual value.
- Folds the Iterable into a `LiveData` accumulator
=> LiveData utilities

gto-support-core/src/main/java/org/ccci/gto/android/common/util/XmlPullParserUtils.java, gto-support-util/src/main/java/org/ccci/gto/android/common/util/xmlpull/CloseableXmlPullParser.kt, gto-support-util/src/test/java/org/ccci/gto/android/common/util/xmlpull/CloseableXmlPullParserTest.kt
a wrapped XmlPullParser that tracks the `InputSource` and closes it when the `XmlPullParser` is closed.
=> Closeable XmlPullParser

gto-support-androidx-lifecycle/src/main/java/org/ccci/gto/android/common/androidx/lifecycle/Lifecycle.kt, gto-support-eventbus/build.gradle, gto-support-eventbus/src/main/java/org/ccci/gto/android/common/eventbus/lifecycle/EventBus.kt, gto-support-eventbus/src/test/java/org/ccci/gto/android/common/eventbus/lifecycle/EventBusLifecycleRegisterTest.kt
This method will register/unregister an EventBus subscriber according to the current lifecycle state
=> Lifecycle aware EventBus.register() extension method

gto-support-androidx-collection/src/main/java/org/ccci/gto/android/common/androidx/collection/LongSparseBooleanArray.kt, gto-support-androidx-collection/src/main/java/org/ccci/gto/android/common/androidx/collection/LongSparseParcelableArray.kt, gto-support-androidx-collection/src/test/java/org/ccci/gto/android/common/androidx/collection/LongSparseBooleanArrayRobolectricTest.kt, gto-support-androidx-collection/src/test/java/org/ccci/gto/android/common/androidx/collection/LongSparseParcelableArrayRobolectricTest.kt
The companion object can't be private because it causes the Parcel logic to throw an `IllegalAccessError`. I also included a unit test to test the actual marshalling & unmarshalling logic.
=> GT-948 Fix IllegalAccessError when unmarshalling LongSparseParcelableArray

gto-support-kotlin-coroutines/src/main/java/org/ccci/gto/android/common/kotlin/coroutines/ReadWriteMutex.kt, gto-support-kotlin-coroutines/src/test/java/org/ccci/gto/android/common/kotlin/coroutines/ReadWriteMutexTest.kt
Unfortunately Kotlin Coroutines doesn't have a native ReadWriteMutex yet. This implements one with basic functionality as a stop-gap solution until they provide an official one.
a `ReadWriteMutex` should function similarly to a `ReadWriteReentrantLock`.
- write access is exclusive, so only a single process can be writing at a time. 
- While a process is writing no other processes can be reading.
- read access is shared, so any number of readers can share the lock at once.
- while any readers exist, a writer will be blocked
This implementation doesn't address fairness for writers, so it is possible for readers to starve out waiting writers. but my current use-cases for this lock uses write access to perform background maintenance, and the background maintenance isn't critical for …
=> Kotlin coroutines ReadWriteMutex

gto-support-androidx-lifecycle/src/main/java/org/ccci/gto/android/common/androidx/lifecycle/ConstrainedStateLifecycleOwner.kt, gto-support-androidx-lifecycle/src/main/java/org/ccci/gto/android/common/androidx/lifecycle/Lifecycle.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/ConstrainedStateLifecycleOwnerTest.kt
This will allow us to define a child LifecycleOwner that constrains the state by `maxState`
=> create a ConstrainedStateLifecycleOwner

build.gradle, gto-support-compat/src/main/java/org/ccci/gto/android/common/compat/graphics/drawable/InsetDrawableCompat.kt, gto-support-compat/src/test/java/org/ccci/gto/android/common/compat/graphics/drawable/InsetDrawableCompatTest.kt
`InsetDrawable` does not take insets into account when returning the intrinsic height or width of the drawable. This is causing a rendering difference on older vs newer versions of Android.
=> GT-964 InsetDrawableCompat

build.gradle, gto-support-androidx-lifecycle/build.gradle, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/ConstrainedStateLifecycleOwnerTest.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/LambdaLifecycleObserverTest.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/LiveDataObserveOnceTest.kt, gto-support-eventbus/build.gradle, gto-support-eventbus/src/test/java/org/ccci/gto/android/common/eventbus/lifecycle/EventBusLifecycleRegisterTest.kt
AndroidX Lifecycle 2.3.0 introduces a new `TestLifecycleOwner` which facilitates testing anything dependent on a `Lifecycle`. This PR switches our existing tests to utilize this new `TestLifecycleOwner` class.
This is on hold until Lifecycle 2.3.0 stable is released
=> Utilize TestLifecycleOwner in tests

build.gradle
Reverts CruGlobal/android-gto-support#773
=> Revert "Bump flipper from 0.76.0 to 0.77.0"

gto-support-androidx-lifecycle/src/main/java/org/ccci/gto/android/common/androidx/lifecycle/CollectionLiveData.kt, gto-support-androidx-lifecycle/src/test/java/org/ccci/gto/android/common/androidx/lifecycle/CollectionLiveDataTest.kt
I needed to add a synchronous mode to `CollectionLiveData` so that observers can fire off immediately on an update to the collection.
In the asynchronous mode, the actual update happens on the next frame, and that is when observers would fire off.
=> GT-1092 Allow synchronous usage of CollectionLiveData

gto-support-picasso/build.gradle, gto-support-picasso/proguard-consumer-requestcreator.pro, gto-support-picasso/src/main/java/com/squareup/picasso/RequestCreatorInternals.kt, gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/RequestCreatorCoroutines.kt, gto-support-picasso/src/test/java/com/squareup/picasso/StubRequestCreator.kt, gto-support-picasso/src/test/java/org/ccci/gto/android/common/picasso/RequestCreatorTest.kt
using `.getBitmap()` within GodTools would occasionally fail to complete. I tracked this down to the fact that the bitmap continuation target was being garbage collected early due to Picasso only holding a weak reference to it.
This PR holds a strong reference to the target as  long as it's processing and adds in task cancellation support so that cancelling an in progress getBitmap will try and cancel the request within Picasso as well.
=> GT-1119 Prevent Picasso Target from being garbage collected too soon

gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/view/PicassoImageView.java, gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/view/SimplePicassoImageView.kt
Updating the image set to the ImageView in the middle of a layout process may not display until a subsequent layout is triggered.
To avoid this behavior we now defer any triggered updates until the layout process isn't running.
=> GT-1133 Fix updates triggered during layout not executing

build.gradle, gto-support-okta/build.gradle, testing/gto-support-okta/build.gradle
Okta changed the artifact name when transitioning from 1.0.18 to 1.0.19
=> upgrade to Okta OIDC 1.0.20

gto-support-picasso/src/main/java/org/ccci/gto/android/common/picasso/material/button/MaterialButtonIconTarget.kt, gto-support-picasso/src/main/res/values/ids.xml, gto-support-picasso/src/test/java/org/ccci/gto/android/common/picasso/material/button/MaterialButtonIconTargetTest.kt
This will allow us to use Picasso to dynamically load an image into a `MaterialButton` icon
=> GT-1136 add a Picasso target for MaterialButton icons

build.gradle, gradle/libs.versions.toml, gto-support-androidx-fragment/build.gradle, gto-support-androidx-lifecycle/build.gradle, gto-support-androidx-viewpager2/build.gradle, gto-support-appcompat/build.gradle, gto-support-lottie/build.gradle, gto-support-picasso/build.gradle, gto-support-realm/build.gradle, gto-support-recyclerview-advrecyclerview/build.gradle, gto-support-recyclerview/build.gradle, gto-support-viewpager/build.gradle, settings.gradle.kts, testing/gto-support-dagger/build.gradle
- move appcompat dependency config to the version catalog
- move configuration of the gradle android plugin to the version catalog
- utilize version catalog for databinding dependencies
- move fragment dependency to version catalog
=> Enable Gradle Version Catalog

gto-support-androidx-fragment/build.gradle, gto-support-androidx-fragment/src/main/java/org/ccci/gto/android/common/androidx/fragment/app/DataBindingDialogFragment.kt
- move appcompat dependency config to the version catalog
- move configuration of the gradle android plugin to the version catalog
- utilize version catalog for databinding dependencies
- create a DataBindingDialogFragment that will use data binding to set the custom view of a dialog
=> GT-1189 Create a DataBindingDialogFragment

gto-support-androidx-databinding/src/main/java/org/ccci/gto/android/common/androidx/databinding/adapters/LifecycleObserverBindingAdapter.kt, gto-support-androidx-databinding/src/main/res/values/ids.xml, gto-support-material-components/src/main/java/org/ccci/gto/android/common/material/button/databinding/MaterialButtonToggleGroupAdapters.kt, gto-support-material-components/src/main/java/org/ccci/gto/android/common/material/slider/databinding/SliderAdapters.kt, gto-support-material-components/src/main/res/values/databinding.xml
- add a binding adapter for binding a view to a LifecycleOwner
- use BindingMethod annotations to avoid needing to define methods
- actually add the onchecked listener
=> Update several BindingAdapters

gto-support-snowplow/src/main/java/org/ccci/gto/android/common/snowplow/events/CustomEvent.kt, gto-support-snowplow/src/main/java/org/ccci/gto/android/common/snowplow/events/CustomEventBuilder.kt, gto-support-snowplow/src/main/java/org/ccci/gto/android/common/snowplow/events/CustomScreenView.kt, gto-support-snowplow/src/main/java/org/ccci/gto/android/common/snowplow/events/CustomStructured.kt, gto-support-snowplow/src/test/java/org/ccci/gto/android/common/snowplow/events/CustomEventTest.kt, gto-support-snowplow/src/test/java/org/ccci/gto/android/common/snowplow/events/CustomScreenViewTest.kt, gto-support-snowplow/src/test/java/org/ccci/gto/android/common/snowplow/events/CustomStructuredTest.kt
Snowplow 3.x removes the builder interface, so this is a migration step
=> Prepare for Snowplow 3.x upgrade

gradle/libs.versions.toml, gto-support-recyclerview/build.gradle.kts, gto-support-recyclerview/src/main/kotlin/org/ccci/gto/android/common/recyclerview/decorator/MarginItemDecoration.kt, gto-support-recyclerview/src/test/kotlin/org/ccci/gto/android/common/recyclerview/decorator/MarginItemDecorationTest.kt
The `MarginItemDecorator` supports adding margin to RecyclerView Items. This will be used by GT-1326 to provide horizontal space to show adjacent cards
=> GT-1326 create MarginItemDecorator

gto-support-androidx-fragment/src/main/kotlin/org/ccci/gto/android/common/androidx/fragment/app/FragmentManager.kt
This provides a sequence over the back stack entries for a FragmentManager. this will allow us to easily search the fragment manager back stack for entries that match a constraint.
=> add a backStackEntries extension val for FragmentManager

gto-support-androidx-fragment/build.gradle.kts, gto-support-androidx-fragment/proguard-consumer.pro, gto-support-androidx-fragment/src/main/kotlin/androidx/fragment/app/FragmentManagerInternals.kt, gto-support-androidx-fragment/src/main/kotlin/org/ccci/gto/android/common/androidx/fragment/app/FragmentManager.kt
this will allow us to more intelligently trigger `executePendingTransactions()`
=> create a FragmentManager.hasPendingActions extension property

gto-support-db-coroutines/build.gradle.kts, gto-support-db-coroutines/src/main/kotlin/org/ccci/gto/android/common/db/CoroutinesFlowDao.kt, gto-support-db-coroutines/src/test/kotlin/org/ccci/gto/android/common/db/CoroutinesFlowDaoTest.kt, gto-support-db-livedata/src/main/kotlin/org/ccci/gto/android/common/db/LiveDataDao.kt, gto-support-db/src/main/java/org/ccci/gto/android/common/db/AbstractDao.kt, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Dao.kt, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Join.kt, gto-support-db/src/main/java/org/ccci/gto/android/common/db/Query.kt, gto-support-db/src/test/java/org/ccci/gto/android/common/db/AbstractDaoClassInvalidationTest.kt, gto-support-db/src/test/java/org/ccci/gto/android/common/db/BaseAbstractDaoTest.kt
- create an internal allTables property on query objects
- support registering arbitrary invalidation callbacks
- use a callbackFlow that monitors invalidations to retrigger evaluation of db query
=> Don't depend on LiveData for gto-support-db-coroutines

gto-support-okta/src/main/kotlin/com/okta/oidc/net/response/TokenResponseInternals.kt, gto-support-okta/src/main/kotlin/org/ccci/gto/android/common/okta/oidc/OktaUserProfileProvider.kt, gto-support-okta/src/main/kotlin/org/ccci/gto/android/common/okta/oidc/clients/sessions/SessionClient.kt, gto-support-okta/src/main/kotlin/org/ccci/gto/android/common/okta/oidc/clients/sessions/SessionClientCoroutines.kt, gto-support-okta/src/main/kotlin/org/ccci/gto/android/common/okta/oidc/clients/sessions/SessionClientLiveData.kt, gto-support-okta/src/main/kotlin/org/ccci/gto/android/common/okta/oidc/net/response/TokenResponse.kt, gto-support-okta/src/test/kotlin/org/ccci/gto/android/common/okta/oidc/net/response/TokenResponseTest.kt
- add an internal method that will "repair" a corrupted TokenResponse
- provide a tokensSafe internal property that attempts to work around a corrupted TokenResponse
=> GT-1402 Workaround a corrupted TokenResponse

gradle/libs.versions.toml, gto-support-okta/build.gradle.kts, gto-support-okta/src/main/kotlin/org/ccci/gto/android/common/okta/oidc/clients/web/SyncWebAuthClient+Coroutines.kt, gto-support-okta/src/test/kotlin/org/ccci/gto/android/common/okta/oidc/clients/web/SyncWebAuthClientCoroutinesTest.kt
- always clear the sessionClient when logging out
- add unit test to make sure we don't clear tokens unless we requested it
=> Fix Okta signout not actually signing out

gto-support-kotlin-coroutines/src/main/kotlin/org/ccci/gto/android/common/kotlin/coroutines/ReadWriteMutex.kt, gto-support-kotlin-coroutines/src/test/kotlin/org/ccci/gto/android/common/kotlin/coroutines/ReadWriteMutexTest.kt
This PR is to fix a deadlock caused by `runBlocking` deadlocking the dispatcher by waiting for a different lock to be released.
- `runBlocking` locks the current thread to the `runBlocking` call and doesn't allow the thread to be used by other coroutines.
- executing `mutex.read.unlock()` on a coroutines dispatcher thread will block that thread and prevent it from being used by other coroutines until `unlock()` finishes
- if `unlock()` has to wait for the `stateMutex` to be released by another coroutine it could deadlock if there are no remaining dispatcher threads to process other coroutines
This could all combine to a deadlock scenario if there is high volume locking/unlocking happening on a `ReadWriteMutex`
=> GT-1423 Fix a dispatcher deadlock caused by using runBlocking

gto-support-kotlin-coroutines/src/main/kotlin/org/ccci/gto/android/common/kotlin/coroutines/ReadWriteMutex.kt, gto-support-kotlin-coroutines/src/test/kotlin/org/ccci/gto/android/common/kotlin/coroutines/ReadWriteMutexTest.kt
There was a race condition when one thread was releasing the last read lock at the same time as another thread was acquiring a new read lock.
=> GT-1440 Fix another ReadWriteMutex race condition

gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/LiveData+Menu.kt, gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/WeakObserver.kt, gto-support-androidx-lifecycle/src/test/kotlin/org/ccci/gto/android/common/androidx/lifecycle/WeakObserverTest.kt
This will allow us to observe a LiveData as long as the menu still exists.
=> GT-1432 LiveData Menu observer

gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/LiveData+ViewModel.kt, gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/LiveData.kt, gto-support-androidx-lifecycle/src/test/kotlin/org/ccci/gto/android/common/androidx/lifecycle/LiveDataViewModelObserverTest.kt
- directly use the Observer interface for ViewModel observers
- support multi-observe on a ViewModel
=> ViewModel LiveData multi-observe

.github/workflows/build.yml, build.gradle.kts, gradle.properties
- make it possible to customize the version when building
- use workflow concurrency to cancel previous executions
- publish snapshots and release builds on tags and PRs
- schedule a SNAPSHOT build once a month and add support for manually triggering a build
=> Publish SNAPSHOT builds for open PRs

gradle.properties, gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/SavedStateHandle+StateFlow.kt, gto-support-androidx-lifecycle/src/test/kotlin/org/ccci/gto/android/common/androidx/lifecycle/SavedStateHandleStateFlowTest.kt
- bump gto-support version
- deprecate getStateFlow() extension if preparation for official getStateFlow support
=> Prepare for AndroidX Lifecycle 2.5

buildSrc/src/main/kotlin/AndroidConfiguration.kt, gradle/libs.versions.toml, gto-support-androidx-compose/src/main/kotlin/org/ccci/gto/android/common/androidx/compose/foundation/text/MinLinesHeightModifier.kt, gto-support-androidx-compose/src/main/kotlin/org/ccci/gto/android/common/androidx/compose/ui/text/Paragraph.kt, gto-support-androidx-compose/src/testDebug/kotlin/org/ccci/gto/android/common/androidx/compose/foundation/text/MinLinesHeightModifierTest.kt, gto-support-androidx-compose/src/testDebug/kotlin/org/ccci/gto/android/common/androidx/compose/ui/text/ParagraphTest.kt
- add a unit test for the minLinesHeight Modifier
- refactor logic to support a computeHeightForDefaultText() method
- add unit test for calculating the height of # of lines of text
=> Expose a method to measure the height of text for a style

gto-support-db/src/main/java/org/ccci/gto/android/common/db/Expression.kt
This avoids using the `in` kotlin keyword for building an expression
=> add `oneOf` methods to Expressions

buildSrc/src/main/kotlin/AndroidConfiguration.kt, gradle.properties, gto-support-androidx-compose/src/test/resources/robolectric.properties, gto-support-compat/src/main/kotlin/org/ccci/gto/android/common/compat/os/BundleCompat.kt, gto-support-compat/src/test/kotlin/org/ccci/gto/android/common/compat/os/BundleCompatTest.kt, gto-support-lottie/src/test/resources/robolectric.properties, gto-support-util/src/main/kotlin/org/ccci/gto/android/common/util/os/Bundle.kt
- compile against API level 33
- create getParcelableArrayCompat method to provide fallback behavior for new API added in Android 13
- target the latest version of Android
=> Upgrade to Android 13

gto-support-androidx-compose-material3/src/main/kotlin/org/ccci/gto/android/common/androidx/compose/material3/ui/text/AnnotatedString+Linkify.kt
This is a performance improvement that avoids needing to run the expensive Linkify logic every time the Text element is recomposed.
=> utilize remember to avoid re-linkifying a string on recomposition

gto-support-api-okhttp3/src/main/java/org/ccci/gto/android/common/api/okhttp3/interceptor/SessionInterceptor.kt, gto-support-api-okhttp3/src/test/kotlin/org/ccci/gto/android/common/api/okhttp3/interceptor/SessionInterceptorTest.kt
This bug surfaced because I was using an anonymous instance of the SessionInterceptor. Which ended up causing Facebook Flipper to crash the app because it doesn't support preference file names that are empty.
relevant crash: [Crashlytics](https://console.firebase.google.com/u/0/project/godtools-b2f82/crashlytics/app/android:org.keynote.godtools.android.debug/issues/d9497696a68602ebda93a0ff03f3a3c0?time=last-seven-days&sessionEventKey=6348349D0364000123C86E75D7EAC283_1732471467181845713)
Changes:
- update SessionInterceptorTest to utilize MockK instead of Mockito
- Prevent an empty string being used as the name of the SessionInterceptor preference file
=> Prevent an empty string being used as the name of the SessionInterceptor preference file

gto-support-util/src/test/kotlin/org/ccci/gto/android/common/util/LocaleRobolectricTest.kt
These unit tests are meant to replace the ones that are targeting deprecated support methods once those deprecated methods are removed
=> add unit tests for Locale.fallback extension values and methods

build.gradle.kts, gradle/libs.versions.toml, gto-support-realm/build.gradle.kts, gto-support-realm/src/main/java/io/realm/RealmRecyclerViewAdapter.java
The library we are copying this from was only available via jcenter, which is currently offline.
This is meant to be temporary until the realm-android-adapters library is released on mavenCentral.
see: https://github.com/realm/realm-android-adapters/pull/162
=> copy RealmRecyclerViewAdapter into gto-support-realm

gto-support-androidx-annotation/build.gradle.kts, gto-support-androidx-annotation/src/androidMain/kotlin/org/ccci/gto/support/androidx/annotation/RestrictTo.android.kt, gto-support-androidx-annotation/src/androidMain/kotlin/org/ccci/gto/support/androidx/annotation/VisibleForTesting.android.kt, gto-support-androidx-annotation/src/commonMain/kotlin/org/ccci/gto/support/androidx/annotation/RestrictTo.kt, gto-support-androidx-annotation/src/commonMain/kotlin/org/ccci/gto/support/androidx/annotation/VisibleForTesting.kt, gto-support-androidx-annotation/src/iosMain/kotlin/org/ccci/gto/support/androidx/annotation/RestrictToScope.ios.kt, gto-support-androidx-annotation/src/jsMain/kotlin/org/ccci/gto/support/androidx/annotation/RestrictToScope.js.kt, settings.gradle.kts
- create a new androidx-annotation multiplatform library
- add mutliplatform definition for VisibleForTesting
- add multiplatform expect for RestrictTo annotation
=> Support a couple AndroidX testing annotations on multiplatform projects

gradle/libs.versions.toml, gto-support-androidx-room/build.gradle.kts, gto-support-androidx-room/src/testFixtures/java/org/ccci/gto/android/common/androidx/room/RoomDatabaseRule.java
This PR creates a junit `Rule` that will provide an instance of a room database that can be used for unit tests.
This will currently be used with a couple different Room databases within GodTools.
=> create a RoomDatabaseRule to aid with Room DB testing

gto-support-jsonapi/proguard-consumer.pro
see: https://issuetracker.google.com/issues/252388315
see: https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md
proguard configuration documentation: https://www.guardsquare.com/manual/configuration/usage
How I tracked it down to this was I discovered the objects being parsed from the API were only partially parsed when they were being saved to the database. The fields missing were the fields where the json attribute names didn't match the field name.
=> GT-1911 when R8 full mode is enabled we need to ensure we keep the annotation classes as well

gto-support-okta/src/main/java/com/okta/authfoundation/credential/SharedPreferencesTokenStorageInternals.java, gto-support-okta/src/main/kotlin/org/ccci/gto/android/common/okta/authfoundation/credential/MigrationTokenStorage.kt, gto-support-okta/src/main/kotlin/org/ccci/gto/android/common/okta/authfoundation/credential/SharedPreferencesTokenStorage.kt, gto-support-okta/src/main/proguard-consumer.pro
A few Android devices have been unable to instantiate `SharedPreferencesTokenStorage` due to not being able to generate encryption keys.
The exception for accessing encryption keys is being thrown on a background thread due to the default behavior of using coroutines to interact with the TokenStorage. The actual exception is being generated when instantiating a private internal val in `SharedPreferencesTokenStorage` which can be manually triggered using reflection.
This PR adds an optional `verify` flag that can be used when creating the `SharedPreferencesTokenStorage` that will "verify" the `TokenStorage` is usable.
Unrelated to this I also introduced a `MigrationTokenStorage` class that will automatically migrate tokens from an old storage mechanism to a new storage mechanism on first …
=> GT-1944 Add a few TokenStorage helpers

.github/workflows/build.yml, buildSrc/src/main/kotlin/MultiplatformConfiguration.kt, gto-support-fluidsonic-locale/src/jsMain/kotlin/org/ccci/gto/support/fluidsonic/locale/PlatformLocale.js.kt
- use a String instead of Intl.Locale for javascript
- target both nodejs and browsers for Kotlin/JS libraries
=> GT-1922 Use a string to represent Locales on js

gto-support-okta-oidc/build.gradle.kts, gto-support-okta-oidc/src/main/kotlin/org/ccci/gto/android/common/okta/oidc/OktaUserProfileProvider.kt, gto-support-okta-oidc/src/test/kotlin/org/ccci/gto/android/common/okta/oidc/BaseOktaOidcTest.kt, gto-support-okta-oidc/src/test/kotlin/org/ccci/gto/android/common/okta/oidc/OktaUserProfileProviderTest.kt, gto-support-okta-oidc/src/test/kotlin/org/ccci/gto/android/common/okta/oidc/clients/sessions/SessionClientCoroutinesTest.kt
- add unit tests for sessionClient.changeFlow() and SessionClient.idTokenFlow()
- cleanup OptIn annotations for OktaUserProfileProvider
- use MockK for the Tokens mock
=> Some updates to gto-support-okta-oidc

gto-support-androidx-room/src/main/kotlin/org/ccci/gto/android/common/androidx/room/RoomDatabase+Coroutines.kt, gto-support-androidx-room/src/testFixtures/java/org/ccci/gto/android/common/androidx/room/RoomDatabaseRule.java, gto-support-androidx-room/src/testFixtures/java/org/ccci/gto/android/common/androidx/room/TestRoomDatabaseCoroutines.java
This will allow us to launch background tasks from within a RoomDatabase. Our immediate need for this is that in GodTools we track a lastAccessed time for Translations. We want to update the timestamp in the background anytime the code actually retrieves the Translation from the database.
=> Support a CoroutineScope for RoomDatabases

gto-support-androidx-lifecycle/build.gradle.kts, gto-support-androidx-lifecycle/src/main/kotlin/androidx/lifecycle/ViewModelInternals.kt, gto-support-androidx-lifecycle/src/main/kotlin/org/ccci/gto/android/common/androidx/lifecycle/LiveData+ViewModel.kt, gto-support-androidx-lifecycle/src/test/kotlin/org/ccci/gto/android/common/androidx/lifecycle/LiveDataViewModelObserverTest.kt, gto-support-androidx-lifecycle/src/testFixtures/java/androidx/lifecycle/ViewModelTestInternals.java
- provide a viewmodel test fixture that allows a test to clear a ViewModel
- switch ViewModel LiveData extensions to utilize addObservable
=> Create some ViewModel testFixtures

gto-support-androidx-compose/src/main/kotlin/org/ccci/gto/android/common/androidx/compose/ui/text/res/AnnotatedStringResources.kt, gto-support-androidx-compose/src/testDebug/kotlin/org/ccci/gto/android/common/androidx/compose/ui/text/res/AnnotatedStringResourcesTest.kt, gto-support-androidx-compose/src/testDebug/res/values/strings.xml
this composable supports taking AnnotatedStrings as format args and preserving any annotations attached to them
=> GT-1985 create an annotatedStringResource() composable

gto-support-jsonapi/src/main/kotlin/org/ccci/gto/android/common/jsonapi/model/JsonApiObject.kt
=> add a source compatible hasErrors() method back to JsonApiObject

gto-support-jsonapi-core/src/main/java/org/ccci/gto/android/common/jsonapi/JsonApiConverter.java, gto-support-jsonapi-core/src/main/kotlin/org/ccci/gto/android/common/jsonapi/internal/util/ObjKey.kt, gto-support-jsonapi-core/src/test/kotlin/org/ccci/gto/android/common/jsonapi/JsonApiConverterCycleRelationshipTest.kt
- convert ObjKey to Kotlin
- handle cycles in the object graph when not including all descendants
- don't include objects in the main data section in the included section
- handle unlimited include depth
=> Handle object cycles when converting to jsonapi

gradle/libs.versions.toml, gto-support-jsonapi-retrofit2/build.gradle.kts, gto-support-jsonapi-retrofit2/src/commonMain/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiConverterFactory.kt, gto-support-jsonapi-retrofit2/src/commonMain/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/annotation/JsonApiFields.kt, gto-support-jsonapi-retrofit2/src/commonTest/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiConverterFactoryTest.kt
- convert to jsonunit-assertj for jsonapi-retrofit2
- add support for a JsonApiFields annotation for retrofit
=> GT-1796 Support a JsonApiFields annotation for retrofit request bodies

gradle/libs.versions.toml, gto-support-androidx-activity/build.gradle.kts, gto-support-androidx-activity/src/main/kotlin/org/ccci/gto/android/common/androidx/activity/result/contract/TransformedActivityResultContract.kt, settings.gradle.kts
- create a new gto-support-androidx-activity module
- add some methods to transform input/output for an existing ActivityResultContract
=> GT-2112 Support transforming input/output for ActivityResultContracts

gto-support-facebook/src/main/kotlin/org/ccci/gto/android/common/facebook/login/AccessToken.kt, gto-support-facebook/src/main/kotlin/org/ccci/gto/android/common/facebook/login/AccessTokenManager.kt, gto-support-facebook/src/test/kotlin/org/ccci/gto/android/common/facebook/login/AccessTokenManagerTest.kt
isAuthenticatedFlow may be a misnomer for this functionality, I'm unsure if token expiration and authentication status are equivalent in the facebook SDK
=> GT-2112 rename isAuthenticatedFlow to isExpiredFlow

gto-support-jsonapi-retrofit2/src/commonMain/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiConverterFactory.kt, gto-support-jsonapi-retrofit2/src/commonTest/kotlin/org/ccci/gto/android/common/jsonapi/retrofit2/JsonApiConverterFactoryTest.kt
- **update JsonApiConverterFactoryTest to utilize kotlin test**
- **validate the specified JsonApiModel is actually support for request bodys and responses**
=> Add eager validation support for the jsonapi retrofit Converter.Factory
